import Foundation

/// Represents the quality and format information for a media stream
public struct VideoFormat {
    public let formatId: String
    public let url: String
    public let resolution: String?
    public let width: Int?
    public let height: Int?
    public let fps: Int?
    public let videoBitrate: Int?
    public let audioSampleRate: Int?
    public let audioBitrate: Int?
    public let fileSize: Int64?
    public let container: String?
    public let videoCodec: String?
    public let audioCodec: String?
    public let isVideoOnly: Bool
    public let isAudioOnly: Bool
    
    public init(formatId: String, url: String, resolution: String? = nil, width: Int? = nil, height: Int? = nil, fps: Int? = nil, videoBitrate: Int? = nil, audioSampleRate: Int? = nil, audioBitrate: Int? = nil, fileSize: Int64? = nil, container: String? = nil, videoCodec: String? = nil, audioCodec: String? = nil, isVideoOnly: Bool = false, isAudioOnly: Bool = false) {
        self.formatId = formatId
        self.url = url
        self.resolution = resolution
        self.width = width
        self.height = height
        self.fps = fps
        self.videoBitrate = videoBitrate
        self.audioSampleRate = audioSampleRate
        self.audioBitrate = audioBitrate
        self.fileSize = fileSize
        self.container = container
        self.videoCodec = videoCodec
        self.audioCodec = audioCodec
        self.isVideoOnly = isVideoOnly
        self.isAudioOnly = isAudioOnly
    }
}

/// Represents subtitle information
public struct Subtitle {
    public let language: String
    public let languageName: String
    public let url: String
    public let format: String
    public let isAutoGenerated: Bool
    
    public init(language: String, languageName: String, url: String, format: String, isAutoGenerated: Bool = false) {
        self.language = language
        self.languageName = languageName
        self.url = url
        self.format = format
        self.isAutoGenerated = isAutoGenerated
    }
}

/// Represents complete video information extracted from YouTube
public struct VideoInfo {
    public let id: String
    public let title: String
    public let description: String?
    public let uploader: String?
    public let uploadDate: String?
    public let duration: Int?
    public let viewCount: Int64?
    public let likeCount: Int64?
    public let thumbnail: String?
    public let formats: [VideoFormat]
    public let subtitles: [Subtitle]
    
    public init(id: String, title: String, description: String? = nil, uploader: String? = nil, uploadDate: String? = nil, duration: Int? = nil, viewCount: Int64? = nil, likeCount: Int64? = nil, thumbnail: String? = nil, formats: [VideoFormat] = [], subtitles: [Subtitle] = []) {
        self.id = id
        self.title = title
        self.description = description
        self.uploader = uploader
        self.uploadDate = uploadDate
        self.duration = duration
        self.viewCount = viewCount
        self.likeCount = likeCount
        self.thumbnail = thumbnail
        self.formats = formats
        self.subtitles = subtitles
    }
}
