import Foundation
import YTDLPSwift
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

/// Example program demonstrating the YouTube extractor functionality
@main
struct YTDLPSwiftExample {
    static func main() async {
        let extractor = YouTubeExtractor()
        
        print("🎥 YTDLPSwift - YouTube Video Information Extractor")
        print("=" * 50)
        
        // Example YouTube URLs to test
        let testURLs = [
            "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            "https://youtu.be/dQw4w9WgXcQ",
            "https://invalid.com/watch?v=test",
            "https://youtube.com/watch"
        ]
        
        for url in testURLs {
            print("\n📍 Testing URL: \(url)")
            
            // Check if URL is valid
            if extractor.isValidYouTubeURL(url) {
                print("✅ Valid YouTube URL")
                
                // Extract video ID
                if let videoId = extractor.extractVideoId(from: url) {
                    print("🆔 Video ID: \(videoId)")
                    
                    // Note: In a real scenario, you would call:
                    // let videoInfo = try await extractor.extractVideoInfo(from: url)
                    // But we'll skip the actual network call for this demo
                    
                    // Create a mock VideoInfo to demonstrate the structure
                    let mockVideoInfo = createMockVideoInfo(videoId: videoId)
                    displayVideoInfo(mockVideoInfo)
                }
            } else {
                print("❌ Invalid YouTube URL")
            }
        }
        
        print("\n🎯 Demonstrating data structures:")
        demonstrateDataStructures()
    }
    
    /// Creates a mock VideoInfo for demonstration purposes
    static func createMockVideoInfo(videoId: String) -> VideoInfo {
        let formats = [
            VideoFormat(
                formatId: "140",
                url: "https://example.com/audio_128k.m4a",
                audioSampleRate: 44100,
                audioBitrate: 128,
                container: "m4a",
                audioCodec: "mp4a.40.2",
                isAudioOnly: true
            ),
            VideoFormat(
                formatId: "298",
                url: "https://example.com/video_720p.mp4",
                resolution: "1280x720",
                width: 1280,
                height: 720,
                fps: 30,
                videoBitrate: 3000,
                container: "mp4",
                videoCodec: "avc1.4d401f",
                isVideoOnly: true
            ),
            VideoFormat(
                formatId: "22",
                url: "https://example.com/video_720p_combined.mp4",
                resolution: "1280x720",
                width: 1280,
                height: 720,
                fps: 30,
                videoBitrate: 2500,
                audioBitrate: 192,
                container: "mp4",
                videoCodec: "avc1.4d401f",
                audioCodec: "mp4a.40.2"
            )
        ]
        
        let subtitles = [
            Subtitle(
                language: "en",
                languageName: "English",
                url: "https://example.com/captions_en.vtt",
                format: "vtt"
            ),
            Subtitle(
                language: "es",
                languageName: "Spanish",
                url: "https://example.com/captions_es.vtt",
                format: "vtt",
                isAutoGenerated: true
            )
        ]
        
        return VideoInfo(
            id: videoId,
            title: "Rick Astley - Never Gonna Give You Up (Official Video)",
            description: "The official video for Never Gonna Give You Up by Rick Astley",
            uploader: "Rick Astley",
            uploadDate: "2009-10-25",
            duration: 213,
            viewCount: 1_400_000_000,
            thumbnail: "https://img.youtube.com/vi/\(videoId)/maxresdefault.jpg",
            formats: formats,
            subtitles: subtitles
        )
    }
    
    /// Displays video information in a formatted way
    static func displayVideoInfo(_ videoInfo: VideoInfo) {
        print("\n📺 Video Information:")
        print("   Title: \(videoInfo.title)")
        print("   Uploader: \(videoInfo.uploader ?? "Unknown")")
        print("   Duration: \(videoInfo.duration ?? 0) seconds")
        print("   Views: \(videoInfo.viewCount ?? 0)")
        
        print("\n🎬 Available Formats:")
        for format in videoInfo.formats {
            var formatDesc = "   \(format.formatId): "
            
            if format.isAudioOnly {
                formatDesc += "Audio Only - \(format.audioBitrate ?? 0)kbps"
            } else if format.isVideoOnly {
                formatDesc += "Video Only - \(format.resolution ?? "Unknown")@\(format.fps ?? 0)fps"
            } else {
                formatDesc += "\(format.resolution ?? "Unknown") - Video: \(format.videoBitrate ?? 0)kbps, Audio: \(format.audioBitrate ?? 0)kbps"
            }
            
            formatDesc += " (\(format.container ?? "unknown"))"
            print(formatDesc)
        }
        
        print("\n💬 Available Subtitles:")
        for subtitle in videoInfo.subtitles {
            let autoGenerated = subtitle.isAutoGenerated ? " (Auto-generated)" : ""
            print("   \(subtitle.language): \(subtitle.languageName)\(autoGenerated)")
        }
    }
    
    /// Demonstrates the data structures used in the library
    static func demonstrateDataStructures() {
        print("\n📋 Data Structures Overview:")
        
        print("\n1. VideoFormat - Represents different quality/format options:")
        print("   • Format ID, URL, resolution, bitrates")
        print("   • Video/audio codec information")
        print("   • Separation of video-only, audio-only, and combined streams")
        
        print("\n2. Subtitle - Represents subtitle tracks:")
        print("   • Language code and human-readable name")
        print("   • URL and format (VTT, SRT, etc.)")
        print("   • Auto-generated vs. manual subtitle detection")
        
        print("\n3. VideoInfo - Complete video metadata:")
        print("   • Basic info: title, uploader, description, duration")
        print("   • Statistics: view count, like count")
        print("   • Arrays of available formats and subtitles")
        
        print("\n4. YouTubeExtractor - Main extraction class:")
        print("   • URL validation and video ID extraction")
        print("   • Async video information extraction")
        print("   • Error handling for various failure scenarios")
    }
}

/// String extension for repeating characters
extension String {
    static func *(lhs: String, rhs: Int) -> String {
        return String(repeating: lhs, count: rhs)
    }
}