import Testing
@testable import YTDLPSwift

@Test func testValidYouTubeURLs() async throws {
    let extractor = YouTubeExtractor()
    
    // Test valid YouTube URLs
    #expect(extractor.isValidYouTubeURL("https://www.youtube.com/watch?v=dQw4w9WgXcQ"))
    #expect(extractor.isValidYouTubeURL("https://youtube.com/watch?v=dQw4w9WgXcQ"))
    #expect(extractor.isValidYouTubeURL("https://m.youtube.com/watch?v=dQw4w9WgXcQ"))
    #expect(extractor.isValidYouTubeURL("https://youtu.be/dQw4w9WgXcQ"))
    #expect(extractor.isValidYouTubeURL("https://www.youtu.be/dQw4w9WgXcQ"))
    
    // Test invalid URLs
    #expect(!extractor.isValidYouTubeURL("https://example.com/watch?v=dQw4w9WgXcQ"))
    #expect(!extractor.isValidYouTubeURL("https://www.youtube.com/watch"))
    #expect(!extractor.isValidYouTubeURL("not-a-url"))
    #expect(!extractor.isValidYouTubeURL(""))
}

@Test func testVideoIdExtraction() async throws {
    let extractor = YouTubeExtractor()
    
    // Test video ID extraction from different URL formats
    #expect(extractor.extractVideoId(from: "https://www.youtube.com/watch?v=dQw4w9WgXcQ") == "dQw4w9WgXcQ")
    #expect(extractor.extractVideoId(from: "https://youtu.be/dQw4w9WgXcQ") == "dQw4w9WgXcQ")
    #expect(extractor.extractVideoId(from: "https://youtube.com/watch?v=dQw4w9WgXcQ&feature=youtu.be") == "dQw4w9WgXcQ")
    
    // Test invalid URLs
    #expect(extractor.extractVideoId(from: "https://example.com/watch?v=dQw4w9WgXcQ") == nil)
    #expect(extractor.extractVideoId(from: "https://www.youtube.com/watch") == nil)
    #expect(extractor.extractVideoId(from: "not-a-url") == nil)
}

@Test func testVideoFormatInitialization() async throws {
    let format = VideoFormat(
        formatId: "22",
        url: "https://example.com/video.mp4",
        resolution: "1280x720",
        width: 1280,
        height: 720,
        fps: 30,
        videoBitrate: 2500,
        audioBitrate: 192,
        container: "mp4",
        videoCodec: "avc1.4d401f",
        audioCodec: "mp4a.40.2"
    )
    
    #expect(format.formatId == "22")
    #expect(format.resolution == "1280x720")
    #expect(format.width == 1280)
    #expect(format.height == 720)
    #expect(format.fps == 30)
    #expect(format.videoBitrate == 2500)
    #expect(format.audioBitrate == 192)
    #expect(!format.isVideoOnly)
    #expect(!format.isAudioOnly)
}

@Test func testSubtitleInitialization() async throws {
    let subtitle = Subtitle(
        language: "en",
        languageName: "English",
        url: "https://example.com/captions_en.vtt",
        format: "vtt",
        isAutoGenerated: false
    )
    
    #expect(subtitle.language == "en")
    #expect(subtitle.languageName == "English")
    #expect(subtitle.url == "https://example.com/captions_en.vtt")
    #expect(subtitle.format == "vtt")
    #expect(!subtitle.isAutoGenerated)
}

@Test func testVideoInfoInitialization() async throws {
    let formats = [
        VideoFormat(formatId: "140", url: "https://example.com/audio.m4a", isAudioOnly: true),
        VideoFormat(formatId: "22", url: "https://example.com/video.mp4", resolution: "1280x720")
    ]
    
    let subtitles = [
        Subtitle(language: "en", languageName: "English", url: "https://example.com/en.vtt", format: "vtt")
    ]
    
    let videoInfo = VideoInfo(
        id: "dQw4w9WgXcQ",
        title: "Test Video",
        description: "A test video",
        uploader: "Test Channel",
        duration: 213,
        viewCount: 1000000,
        thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
        formats: formats,
        subtitles: subtitles
    )
    
    #expect(videoInfo.id == "dQw4w9WgXcQ")
    #expect(videoInfo.title == "Test Video")
    #expect(videoInfo.description == "A test video")
    #expect(videoInfo.uploader == "Test Channel")
    #expect(videoInfo.duration == 213)
    #expect(videoInfo.viewCount == 1000000)
    #expect(videoInfo.formats.count == 2)
    #expect(videoInfo.subtitles.count == 1)
}

@Test func testYouTubeExtractorErrors() async throws {
    let extractor = YouTubeExtractor()
    
    // Test invalid URL error
    do {
        _ = try await extractor.extractVideoInfo(from: "https://example.com/invalid")
        #expect(Bool(false), "Should have thrown an error")
    } catch YouTubeExtractorError.invalidURL {
        // Expected error
        #expect(Bool(true))
    } catch {
        #expect(Bool(false), "Wrong error type thrown: \(error)")
    }
    
    // Test video ID not found error (valid YouTube domain but no video ID)
    do {
        _ = try await extractor.extractVideoInfo(from: "https://youtube.com/playlist")
        #expect(Bool(false), "Should have thrown an error")
    } catch YouTubeExtractorError.videoIdNotFound {
        // Expected error  
        #expect(Bool(true))
    } catch YouTubeExtractorError.invalidURL {
        // This is also acceptable since no video ID means invalid for our purposes
        #expect(Bool(true))
    } catch {
        #expect(Bool(false), "Wrong error type thrown: \(error)")
    }
}
